### ISSUE TITLE
Draw to the screen directly without creating a window?

### ISSUE THREAD

**Issue by breandan** [JetBrains/skija#100]
I would like to create a transparent stage which overlays the screen contents without creating a window. Does Skia support drawing pixels to the screen directly without creating a canvas or window?

**Comment by tonsky** [comment]
The idea is that you create a window yourself, initialize OpenGL context, and then pass that to Skija. Skija itself does not manage windows or drawing contexts.

I would love to point you to some examples of creating transparent windows, but I don’t know any.

**Comment by breandan** [comment]
Ah, now I understand. Thank you for the pointer! For anyone else who might have this question, [the Javadocs have an example](https://docs.oracle.com/javase/tutorial/uiswing/misc/trans_shaped_windows.html) for create a transparent/translucent window. The following ended up worked for me on Ubuntu 18.04:

```
import org.jetbrains.skija.Canvas
import org.jetbrains.skija.Paint
import org.jetbrains.skija.RRect
import org.jetbrains.skiko.SkiaRenderer
import org.jetbrains.skiko.SkiaWindow

fun main() {
    SkiaWindow().apply {
        layer.renderer = Renderer { renderer, w, h ->
            val canvas = renderer.canvas!!
            val paint1 = Paint().setColor(0xffff0000.toInt()).setAlpha(100) // ARGB
            canvas.drawRRect(RRect.makeLTRB(10f, 10f, w - 10f, h - 10f, 5f), paint1)
            val paint2 = Paint().setColor(0xff00ff00.toInt()).setAlpha(100) // ARGB
            canvas.drawRRect(RRect.makeLTRB(30f, 30f, w - 30f, h - 30f, 10f), paint2)
        }

        isUndecorated = true
        opacity = 0.85f
        isVisible = true
        setSize(800, 600)
    }
}

class Renderer(val displayScene: (Renderer, Int, Int) -> Unit): SkiaRenderer {
    var canvas: Canvas? = null

    override fun onRender(canvas: Canvas, width: Int, height: Int, nanoTime: Long) {
        this.canvas = canvas
        displayScene(this, width, height)
    }
}
```
