### ISSUE TITLE
DirectContext.flush() taking more than 16 ms

### ISSUE THREAD

**Issue by JasonTheKitten** [JetBrains/skija#105]
Hello.
The target refresh rate of an application is typically 60 frames per second. 1000/60 = 16 ms, so we have 16 milliseconds to work with per frame (when displaying animations).
Problem is, at least on my modern computer, DirectContext.flush() is taking about 30 ms per frame, so that framerate cannot be maintained.
Is there any way you can make this quicker? If not, is there an alternative I can use?

(Windows OS)

**Comment by tonsky** [comment]
Are you rendering a lot? Do you have a discrete graphics card? Normally flush() is not a bottleneck. What’s your frame time (before flush)?

**Comment by JasonTheKitten** [comment]
(Sorry, not at home rn, will give more info when I am home)

**Comment by JasonTheKitten** [comment]
Ok, I see what's going on
The first `flush()` after creating a canvas is a bit slower than usual. In my case, I was creating a new canvas every frame, so that's fixed by me not being stupid.

**Comment by tonsky** [comment]
That’s a popular mistake! Many people tend to create context or canvas every frame. Gotta think what I can do about it

**Comment by tonsky** [comment]
Glad this is resolved!
