### ISSUE TITLE
Add Perlin noise shader support

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/skija#128]
https://github.com/JetBrains/skija/blob/master/shared/java/Shader.java does not have the bindings to make fractal noise / turbulence shaders that are available in Skia - https://api.skia.org/classSkPerlinNoiseShader.html

If Skija is going to be deprecated, please add this in Skiko's ongoing work

**Comment by kirill-grouchnikov** [comment]
@igordmn @olonho - for your consideration. I'd love to be able to use Skia's noise shaders instead of implementing my own. These are useful for any noise-based texturing of surfaces for Compose.

**Comment by tonsky** [comment]
Thank you for the suggestion. This should be trivial to add — will do when I get back from the vacation

**Comment by kirill-grouchnikov** [comment]
Forgot to update here - I've added them in https://github.com/JetBrains/skiko/pull/165 but didn't see the matching change in (maybe incomplete yet) https://github.com/JetBrains/skiko/pull/167

**Comment by kirill-grouchnikov** [comment]
Ah, they are in https://github.com/JetBrains/skiko/blob/master/skiko/src/macosX64Main/cpp/generated/Shader.cc as well. This can be closed now
