### ISSUE TITLE
Animation with image

### ISSUE THREAD

**Issue by justicezxz** [JetBrains/skija#129]
hi,
how to render animation with image?
use json file containing Base64 pictures.
I found that skia can do it.

thanks

**Comment by tonsky** [comment]
what format are those pictures in? after base64 decoding?

**Comment by justicezxz** [comment]
Yes, like this JSON file
https://skottie.skia.org/c16eee287f2cea44102b6670c66e60ab?h=1000&w=1000

**Comment by tonsky** [comment]
Ok, this format is Lottie. We have an example scene here https://github.com/JetBrains/skija/blob/master/examples/scenes/src/SkottieScene.java

**Comment by justicezxz** [comment]
Yes, I tried,
but the picture in JSON is not displayed

**Comment by xiaoxiao-wzj** [comment]
hi, 
I also encountered this problem, if there are pictures in json, how can I load pictures

**Comment by tonsky** [comment]
If you share your source code I might be able to help you

**Comment by justicezxz** [comment]
just run the example with this json file
looks like image resource is not loaded

[json.txt](https://github.com/JetBrains/skija/files/7129850/json.txt)

**Comment by tonsky** [comment]
Oh, I see. I think those are just not supported in Skia. You can open an issue here https://bugs.chromium.org/p/skia/issues/list?q=Area%3DSkottie&can=2

**Comment by xiaoxiao-wzj** [comment]
![image](https://user-images.githubusercontent.com/53417819/132609028-6f2f9d6c-908d-49e6-accd-18b0a012b730.png)

For pictures, skija needs to add ResourceProvider to specify the way to load resources, just like fonts

**Comment by justicezxz** [comment]
please add these two lines in AnimationBuilder.cc 
```
extern "C" JNIEXPORT jlong JNICALL Java_org_jetbrains_skija_skottie_AnimationBuilder__1nBuildFromFile
  (JNIEnv* env, jclass jclass, jlong ptr, jstring pathStr) {
    Animation::Builder* instance = reinterpret_cast<Animation::Builder*>(static_cast<uintptr_t>(ptr));
    SkString path = skString(env, pathStr);
    auto resource_provider =
		skresources::CachingResourceProvider::Make(
			skresources::DataURIResourceProviderProxy::Make(
				skresources::FileResourceProvider::Make(SkOSPath::Dirname(path.c_str()),
														/*predecode=*/true),
				/*predecode=*/true));
    instance->setResourceProvider(std::move(resource_provider));
    sk_sp<Animation> animation = instance->makeFromFile(path.c_str());
    return reinterpret_cast<jlong>(animation.release());
}

```

**Comment by tonsky** [comment]
I’ll take a look next week!

**Comment by tonsky** [comment]
I’ve added all three resource providers as classes to skija.resources package. See https://github.com/JetBrains/skija/blob/e265802686173485b3cc03bf6c9dca2fd364a5ed/examples/scenes/src/SkottieScene.java#L43 for an example. Source code is here, but for jars there have been some maven deployment issues, hopefully will fix them next week

**Comment by tonsky** [comment]
Deployed as 0.93.4
