### ISSUE TITLE
Missing RuntimeEffect instance.makeColorFilter

### ISSUE THREAD

**Issue by bumfo** [JetBrains/skija#135]
In C++ Skia, first RuntimeEffect::makeForColorFilter is called to created RuntimeEffect instance, then instance.makeColorFilter is called to convert it to color filter. In Skija, instance.makeColorFilter is missing so there's no way to create a color filter from RuntimeEffect.

**Comment by tonsky** [comment]
Fixed in https://github.com/HumbleUI/Skija/commit/4620befb3b4e0a68e721138991ea658252e372f5. This repo is no longer supported, so I recommend switching to https://github.com/HumbleUI/Skija. Version 0.98.1 should be out soon with `RuntimeEffect::makeColorFilter` in it
