### ISSUE TITLE
Unable to build the demo app

### ISSUE THREAD

**Issue by suyashjoshi** [JetBrains/skija#140]
I was very excited to try this project - [demo app](https://github.com/JetBrains/skija/tree/master/examples/lwjgl)  and run the samples but the getting started step is failing with the following error:

**./script/build.py**

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>`

After doing clean and build, it gave me a different error:

```
Traceback (most recent call last):
  File "./script/build.py", line 88, in <module>
    sys.exit(main())
  File "./script/build.py", line 26, in main
    with zipfile.ZipFile(zip, 'r') as f:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Any idea how to resolve this issue?

**Comment by tonsky** [comment]
Yes, there must me a zero-length zip file in `platform` directory. Remove it and try again with Python 3.

P.S. Consider switching to https://github.com/HumbleUI/Skija/, this repo is not updated anymore

**Comment by suyashjoshi** [comment]
ok, I'll just try the repo in other location. Thanks
