### ISSUE TITLE
Support for GrDirectContext::MakeGL with GrGLInterface

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [JetBrains/skija#143]
It would be useful to be able to specify a `GrGLInterface` when creating an OpenGL `DirectContext`. This would allow better integration into existing applications using OpenGL that need more control over the OpenGL state. At the moment Skia will modify the GL state on its own making it harder for applications to keep track of it.

**Comment by tonsky** [comment]
Sure. Patch?

**Comment by Sm0keySa1m0n** [comment]
Didn't realise this repo wasn't supported anymore, should I reopen the issue in https://github.com/HumbleUI/Skija ?

**Comment by tonsky** [comment]
Oh yeah, sorry, I didn’t look at the organization. Yes it’s in Humble UI now

**Comment by Sm0keySa1m0n** [comment]
Reponed in https://github.com/HumbleUI/Skija/issues/22.
