### ISSUE TITLE
JetBrainsRuntime and SkijaGraphics2D a possibility?

### ISSUE THREAD

**Issue by safasofuoglu** [JetBrains/skija#25]
Great project and great initiative! I love how you approach this from the perspective of stability and memory consistency.

I understand this is a multi-purpose project and JetBrains has interesting plans. I'd like to point out a possibility that gets me excited: A jbr/java2d graphics environment based on skija.

Why:
- Current java2d graphics environments are platform-specific implementations. It seems quite pragmatic to depend on skija and offload cross-platform support to skia.
- Current java2d font rendering is inferior to skia on both windows and mac (UI fonts kerning and possibly other issues)
- Fractional scaling on windows sucks (for intellij products, on 150%, inconsistent left-right border widths), which can be solved with skia.

What would this enable:
- Proper, consistent, performant rendering cross-platform
- Rendering extensions/capabilities for svg, smooth animations and other stuff
- Target metal on mac as an alternative to project lanai
- Run intellij platform on fuchsia and nest thermostat
- WinUI-based AWT toolkit using skia (first class D3D12 support is coming soon)

**Comment by tonsky** [comment]
Thank you @safasofuoglu. If you can run Skia in JVM, sky is the limit! You make a very solid case, thank you!
