### ISSUE TITLE
libc++abi.dylib: Pure virtual function called!

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#26]
Hi !

This happen from time to time.
No more info displayed.

Thanks

**Comment by tonsky** [comment]
Any clues on what are you doing when this happens?

**Comment by Solido** [comment]
Batch rendering may be the cause.
Async state between Java / C ?

**Comment by Solido** [comment]
Details: 
`Executors.newFixedThreadPool(4)`
then submit each task
`surface = Surface.makeRasterN32Premul(width, height) ...`

**Comment by tonsky** [comment]
Okay, so you are doing it from multiple thread simultaneously. Frankly, I have no idea which Skia calls are multithread-safe and which are not. The Skija wrapper does not add anything on top of it (I hope) so must be a problem with Skia internals. I recommend you check that the calls you are making are actually safe and can be invoked from multiple threads.

**Comment by Solido** [comment]
Yep thank you ! 
I close but at least we have a note for later.
