### ISSUE TITLE
How to use PathEffect MakeSum

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#27]
Hello,

I'm trying to use `makesum` with a path. 
I saw that _makesum is here but I think it's internal only ?

Love this package ! 
thx

**Comment by tonsky** [comment]
Here is the method https://github.com/JetBrains/skija/blob/57fc2aeb1e4799c83115c5ab9d567168cc5596cb/src/main/java/org/jetbrains/skija/PathEffect.java#L18

And here is an example

https://github.com/JetBrains/skija/blob/6ef7c27fa92e199f98d5e70e78998490303efae6/examples/lwjgl/src/main/java/org/jetbrains/skija/examples/lwjgl/PathEffectsScene.java#L36

**Comment by Solido** [comment]
I was looking at the wrong place looking for a static method makeSum(p1,p2),
using the instance is more simple. 
Thanks for the quick answer !

**Comment by tonsky** [comment]
Yeah. I don’t always understand the logic why some constructors are static but other are instance methods.
