### ISSUE TITLE
Unable to load skija.so in lwjgl exmaple.

### ISSUE THREAD

**Issue by sameep-baraiya** [JetBrains/skija#29]
Where is skjia.so is located. I am building project (lwjgl-intellij) using gradle on linux.

**Comment by tonsky** [comment]
Check target/native

**Comment by sameep-baraiya** [comment]
I project external libraries:
- 
![Screenshot from 2020-08-30 14-16-21](https://user-images.githubusercontent.com/32372641/91655072-b4c08d00-eacb-11ea-8061-32f7312d8fc2.png)
-
How to tell gradle load skija.so ?

**Comment by tonsky** [comment]
Oh, this jar only has mac version at the moment. This will change in the future. For now, you’ll need to build skija jar yourself

**Comment by tonsky** [comment]
There is now a linux build of Skija which can start the lwjgl example on Ubuntu. Might still have some rought edges, though.

You can consume it from:

```
org.jetbrains.skija:skija-linux:0.4.48
```

**Comment by sameep-baraiya** [comment]
After that when i try to run code it shows:
` /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/skija_4625412185375/libskija.so)`
complete log:
`/home/sameep/openjfx/java/jdk-14.0.1/bin/java -javaagent:/snap/intellij-idea-community/252/lib/idea_rt.jar=45943:/snap/intellij-idea-community/252/bin -Dfile.encoding=UTF-8 -classpath /home/sameep/Desktop/skija/skija/examples/lwjgl/target/classes:/home/sameep/.m2/repository/org/jetbrains/skija/skija-linux/0.4.48/skija-linux-0.4.48.jar:/home/sameep/.m2/repository/org/jetbrains/skija/skija-shared/0.4.48/skija-shared-0.4.48.jar:/home/sameep/.m2/repository/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3.jar:/home/sameep/.m2/repository/org/lwjgl/lwjgl-glfw/3.2.3/lwjgl-glfw-3.2.3.jar:/home/sameep/.m2/repository/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3.jar:/home/sameep/.m2/repository/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3-natives-linux.jar:/home/sameep/.m2/repository/org/lwjgl/lwjgl-glfw/3.2.3/lwjgl-glfw-3.2.3-natives-linux.jar:/home/sameep/.m2/repository/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-linux.jar org.jetbrains.skija.examples.lwjgl.Main
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/skija_4625412185375/libskija.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/skija_4625412185375/libskija.so)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
	at java.base/java.lang.Runtime.load0(Runtime.java:745)
	at java.base/java.lang.System.load(System.java:1871)
	at org.jetbrains.skija.Library._load(Library.java:57)
	at org.jetbrains.skija.Library.load(Library.java:27)
	at org.jetbrains.skija.examples.lwjgl.Window.loop(Main.java:278)
	at org.jetbrains.skija.examples.lwjgl.Window.run(Main.java:60)
	at org.jetbrains.skija.examples.lwjgl.Main.main(Main.java:21)

Process finished with exit code 1
`
`$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
`
![Screenshot from 2020-09-26 14-35-35](https://user-images.githubusercontent.com/32372641/94337119-aa7bab00-0005-11eb-9577-73f168fe1379.png)

What should i do next ?

**Comment by tonsky** [comment]
I guess we need to build with an earlier glibc version, we’ll look into it!

**Comment by tonsky** [comment]
Can you try with 0.4.59? I just rebuilt it on Ubuntu 16.04. Thanks!

**Comment by sameep-baraiya** [comment]
It's working now ! Thank You. :)
![Screenshot from 2020-09-28 23-42-15](https://user-images.githubusercontent.com/32372641/94469834-60045500-01e4-11eb-8edb-815b4c58e9b8.png)

**Comment by tonsky** [comment]
Let me know if something seems broken, we develop on macOS and did not test it thoroughly on Linux yet
