### ISSUE TITLE
Image formats HEIF, WebP

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#30]
Hi !

Following your previous hint my program export snapshot as PNG but it's not great for some details
How can it export to HEIF ?

Edit: found some docs here https://skia.googlesource.com/skia/+/master/include/core/SkEncodedImageFormat.h
but I guess you need to do all the code wiring.

Thanks

**Comment by tonsky** [comment]
Will put it on the queue, thanks!

P.S. What’s not great about details in PNG? It’s loseless

**Comment by Solido** [comment]
Thanks @tonsky !
PNG is lossless and got transparency but it does not handle well gradients where event JPG is better.

**Comment by Solido** [comment]
<img width="171" alt="Screen Shot 2020-09-23 at 20 33 35" src="https://user-images.githubusercontent.com/1295961/94054581-1da1d900-fddc-11ea-81e5-90e54033a4e2.png">

An example of broken gradients.

I'm starting to get some results with the lib and also learning skia following your commits.
Thank you.

**Comment by tonsky** [comment]
Got JPEG and WEBP hooked up, should be in v0.4.51. HEIF requires Skia reconfiguration, postponed for now.

**Comment by Solido** [comment]
@tonsky Thanks !
Way better rendering using Jpg
