### ISSUE TITLE
Bindings requests

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#32]
Hi !

Thanks for Color4f, code is now much more direct.

Instead of opening a ticket each time I'd like to suggest a list of methods & maybe influence you in your implementation priorities...

Thanks !

- [x] Canvas drawTextOnPath
- Gradient with SkPoint instead of float (help a lot with sugar syntax / conversions)
- Canvas.saveLayer with Rect

Errors 

- [x] color4f OK on gradient but UnsatisfiedLinkError on Paint

Also I've never linked Java to C but maybe later I'll be able to connect some API calls.

**Comment by tonsky** [comment]
Ok thanks, I’ll get back to it approx in two weeks, after some vacation time :)

**Comment by tonsky** [comment]
Hi @Solido, I have couple of questions:

> Canvas drawTextOnPath

Canvas does not seem to have drawTextOnPath. Seems like it could be implemented with `PathMeasure` (which I just added) and `TextBlob::MakeFromRSXform` (which I will add soon) should be enough. Unless I am missing something?

> color4f OK on gradient but UnsatisfiedLinkError on Paint

Seems to work in my example: https://github.com/JetBrains/skija/blob/b0ae840f5c8bb8035d6509f5889182aa42532ee5/examples/lwjgl/src/main/java/org/jetbrains/skija/examples/lwjgl/ShadersScene.java#L16-L55. Can you still reproduce it? Can you share a code example?

**Comment by Solido** [comment]
Hi @tonsky 
Hope you add good holidays !

More info drawOnPath
https://skia.org/user/api/bmh_SkPath?cl=9919
https://github.com/mono/SkiaSharp/issues/1183

If color4f works on your code then it's on my side !
Currently I compile libskija.dylib and put it in my resources folder.

For the lib I also to local maven then 
```
api "org.jetbrains.skija:skija:0.0.0-local"
api "org.jetbrains.skija:skija:0.0.0-local-natives-mac-x64"
```

Done the full process but color4f is not even found while on the ide ...

How can I better follow your coming updates ? 
Is it possible to have it linked by using a common maven repo ?

So far it's working great, Thanks

**Comment by tonsky** [comment]
Right now we publish jar with native macOS dylib at https://bintray.com/beta/#/jetbrains/skija/skija?tab=overview. If you are on a mac, you can depend on those. Those are published per every commit. E.g. 0.4.35 contains your request on gradient points and saveLayer with Rect.

In the future we are going to split single jar into separate `skija` and `skija-natives-mac` and introduce other platforms.

**Comment by tonsky** [comment]
Re: drawOnPath. It seems that it was at one point in Skia, but has been removed since. The solution would be to reimplement it with the existing primitives.

**Comment by Solido** [comment]
<img width="241" alt="Screen Shot 2020-09-16 at 01 53 04" src="https://user-images.githubusercontent.com/1295961/93276264-6562a800-f7bf-11ea-8281-9bddccafc0ef.png">

Still lot of work but slowly starting to get some results.
Using the correct jar solved the problems.

**Comment by tonsky** [comment]
Ok, I have now pushed all the necessary primitives to implement text on path. Since it is no longer in Skia, I am not putting dedicated textOnPath method into Skija, but it is simple enough to implement. Please take a look:

https://github.com/JetBrains/skija/blob/dfa6084c4ba396044701d1b31de43d6b52398881/examples/lwjgl/src/main/java/org/jetbrains/skija/examples/lwjgl/TextBlobScene.java#L64-L97

This is what I am getting:

<img width="701" alt="Screenshot 2020-09-16 at 17 04 51" src="https://user-images.githubusercontent.com/285292/93355963-eb720380-f83e-11ea-9269-60e7afbd39fd.png">

**Comment by Solido** [comment]
That was fast ! :D

**Comment by tonsky** [comment]
JFYI @Solido artifacts coordinates changed a little. Published versions now look like this:

```
org.jetbrains.skija:skija-macos:0.4.48
```

And local ones (installed via `./script/install.sh`) are:

```
org.jetbrains.skija:skija-platform:0.0.0-SNAPSHOT
```

See README for more details.

**Comment by tonsky** [comment]
Oh, and the repo changed to. We now host it in JetBrains Space https://packages.jetbrains.team/maven/p/skija/maven instead of bintray.

**Comment by Solido** [comment]
Thanks @tonsky !
All updated with the new repo
