### ISSUE TITLE
Binding requests

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#34]
Hi

Here I put some some non-connected features that I found when coding with Skija.
I'll list more as I explore the API.

- [x] path.rewind()
- [ ] path.drawPatch()
- [x] path.drawPoints using Points

Cheers

**Comment by tonsky** [comment]
Path.rewind is there
Canvas.drawPoints is actually three separate methods in Canvas: drawPoints, drawLines and drawPolygon (one per PointMode)

**Comment by tonsky** [comment]
I’ll add drawPoints, drawLines and drawPolygon versions that take an array of points

**Comment by tonsky** [comment]
All added in 0.4.58

**Comment by Solido** [comment]
Much appreciated @tonsky !
