### ISSUE TITLE
Drawable

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#35]
Hi !

My stuffs are getting more complex using Skija and I'd like to refactor to Kotlin objects drawn as SK Drawable.
Do you have an estimation for landing this feature in your roadmap ?

Thanks  !

**Comment by tonsky** [comment]
How do you imagine this would look like? SkDrawable seems to be something Skia itself uses for internal code organization, I don’t understand how it fits into the user code?

If you want to cache draw commands and call them efficiently maybe Picture/PictureRecorder would be a better fit?

**Comment by Solido** [comment]
Drawable is a natural pattern that emerge when yours drawings are getting more complex and you need to organize and optimize.

I already use Picture Recorder but currently I manage myself data objects that are later rendered to the canvas but without optimization because I create the canvas, draw on picture recorder etc for each object.

By looking at Microsoft bindings I found this
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skdrawable?view=skiasharp-1.68.2

And this would simplify my works a lot because I would not store data object anymore but rendering configurations that delegate optimization and dirty state for me. Generating a new ID would indicate to the render pipeline to redraw. This is completely the Widget object that you can find in Flutter.

I'm drawing millions of objects and looking for animations later currently it took too much milliseconds to render.

Not trivial nor high priority on skija roadmap but definitively unavoidable when moving to higher level rendering.

Thanks !

**Comment by tonsky** [comment]
Sorry, I still don’t get it. Can you give me more concrete example, imagine you already have Drawable API, how would it look like?

PictureRecorder gives you Picture, which is as cacheable as any Drawable is. Can you explain again, what exactly doesn’t work for you here?

**Comment by Solido** [comment]
OK ! Let's see if we can find something actionable

Let's say that currently code is like

```
val hugeArray = smth.map((s) -> initSmth())
hugeArray[999].changeSmth()

for(smth in hugeArray) {
  canvas.apply {
     move
     line
     curve
     etc
  }
}
```

Each modification to the java object should redraw.

you can do something else and **manage yourself** the object and create a render() that would return a Picture is smth is updated BUT you still need to call 

`hugeArray.drawPicture()` for each entry !

But would it be more convenient to have

```
ConfigObject extends Drawable {
   color4f color

  setColor (newcolor) {
    color = newcolor
    notifyDrawingChanged () // from the skia API
  }
  
  // This will snapshot as Picture but not my programming charge, I rely on skia which is better !
  draw(canvas) {
    ...
  }

}
```

And now I can do

```
val hugeConfigs = List<ConfigObjects>().map( init ...)

hufeConfigs.forEach( canvas.drawDrawable(it)) // Snapshot each instance

hugeConfigs[300].color4f = Orange

hufeConfigs.forEach( canvas.drawDrawable(it)) // Only redraw updated instance and compose snapshot
```

Which is much more readable and convenient.

When program start to grow we naturally move to this encapsulation pattern.

I can program my own using PictureRecorder but so every devs using Skija would have to do it too.

SKDrawable is part of Skia so we're expecting to find an equivalent.

I need to refactor my program because as for now it's a chain of functions calls where it should be more object oriented and SKDrawable pattern fill this need.

Hope I've clarified my point, thanks for reading.

**Comment by tonsky** [comment]
Ok I think I see it now, thanks for clarifying. The question is not in the ability to do it, but in comfort of having an already bundled version, correct?

I imagine something like this for the interface, would that work for you? Later we could redo the implementation to use native SkDrawable under the hood.

```java
public abstract class Drawable implements Closeable {
    public Picture _picture;

    public void notifyDrawingChanged() {
        if (_picture != null)
            _picture.close();
        _picture = null;
    }

    public void draw(Canvas c, Matrix33 matrix) {
        int saveCount = c.save();
        if (matrix != null)
            c.concat(matrix);
        if (_picture != null)
            c.drawPicture(_picture);
        else {
            try (var recorder = new PictureRecorder()) {
                Rect bounds = getBounds();
                recorder.beginRecording(bounds, true);
                onDraw(c);
                _picture = recorder.finishRecordingAsPicture(bounds);
            }
        }
        c.restoreToCount(saveCount);
    }

    public Rect getBounds() { 
        return onGetBounds();
    }

    public abstract void onDraw(Canvas s);

    public abstract Rect onGetBounds();

    public void close() {
        if (_picture != null)
            _picture.close();
    }
}
```

**Comment by Solido** [comment]
Thanks for the first implementation !
I'll try to refactor my program using it.

At first I was thinking of `Drawable` as a convenience but now I see it as a mandatory good practice for **Skija**
Maybe later some more milliseconds can be gained by relying on native impl.

**Comment by tonsky** [comment]
Ok I added native Drawables to 0.4.72 but I don’t think they do what you expect them to do. At least I couldn’t force them to not call onDraw() on every draw() call. Maybe I miss something, but reading this:

```
/**
 *  Base-class for objects that draw into SkCanvas.
 *
 *  The object has a generation ID, which is guaranteed to be unique across all drawables. To
 *  allow for clients of the drawable that may want to cache the results, the drawable must
 *  change its generation ID whenever its internal state changes such that it will draw differently.
 */
```

I don’t see anything that promises caching behavior. Clients _might_ cache, but that doesn’t mean they will.

**Comment by Solido** [comment]
Thanks @tonsky I think it's a good start and I can use it now +1
In the future if someone want to build a framework on top of Skija this kind of classes would be helpful.
