### ISSUE TITLE
Generating cc files

### ISSUE THREAD

**Issue by sgopi93** [JetBrains/skija#36]
Hi, I want to contribute Skija by writing binding for Skia's PDF module. As I am new to JNI, I want to know cc files are generated using any script or written. Maybe it is a dumb question but I do not know exactly where to start to write the binding.

**Comment by tonsky** [comment]
You are welcome to! CCs are hand-written. They’re pretty simple 1-to-1 translation from what you expect from Java. Better start by studying how other modules/methods are implemented. Also take a look at https://github.com/JetBrains/skija/blob/master/docs/Conventions.md
