### ISSUE TITLE
Native files not loading

### ISSUE THREAD

**Issue by sgopi93** [JetBrains/skija#39]
Hi, I have tried a kotlin project with skija with 'org.jetbrains.skija:skija:0.4.39'. when I run the project I get "java.lang.UnsatisfiedLinkError: org.jetbrains.skija.Paint._nGetFinalizer()J" Am i missing something

**Comment by sgopi93** [comment]
Sorry!. I did not know we need to call Library.load() manually to use skija APIs. It would be better if we convey the need of Library loading in a better way.

**Comment by tonsky** [comment]
Yes, I have plans to do this automatically, thanks for reminding!
