### ISSUE TITLE
Can't run LWJGL example on macOS

### ISSUE THREAD

**Issue by alexdmiller** [JetBrains/skija#55]
16-in Macbook, macOS 10.15.7

When I run `./script/install.sh` I get:

```
Using Skia from /Users/miller/Projects/skija/native/Skia-m88-59bafeeaa7-macos-Release-x64
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

Not surprisingly, given those errors, when I try to run the LWJGL example:

```
$ cd examples/lwjgl 
README.md	fonts		images		lwjgl.iml	pom.xml		script		src		texts
$ ./script/exec.sh
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.442 s
[INFO] Finished at: 2020-11-18T18:26:28-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lwjgl: Could not resolve dependencies for project org.jetbrains.skija.examples:lwjgl:jar:0.1.0: Could not find artifact org.jetbrains.skija:skija-native:jar:0.0.0-SNAPSHOT in space-maven (https://packages.jetbrains.team/maven/p/skija/maven) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by tonsky** [comment]
Seems like you need Ninja. `brew install ninja`

**Comment by zikajk** [comment]
I have got another issue - also on MacOS.

at /var/folders/d4/3mjqr9016f15pcml1093msv40000gn/T/clojure-7099341837735130772.edn
{:clojure.main/message
 "Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).\n-X (No such file or directory)\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line -2,
  :clojure.error/cause "-X (No such file or directory)",
  :clojure.error/symbol java.io.FileInputStream/open0,
  :clojure.error/source "FileInputStream.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.io.FileNotFoundException,
    :message "-X (No such file or directory)",
    :at [java.io.FileInputStream open0 "FileInputStream.java" -2]}],
  :trace
  [[java.io.FileInputStream open0 "FileInputStream.java" -2]
   [java.io.FileInputStream open "FileInputStream.java" 212]
   [java.io.FileInputStream <init> "FileInputStream.java" 154]
   [java.io.FileInputStream <init> "FileInputStream.java" 109]
   [clojure.lang.Compiler loadFile "Compiler.java" 7571]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$script_opt invokeStatic "main.clj" 535]
   [clojure.main$script_opt invoke "main.clj" 530]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "-X (No such file or directory)"}}

**Comment by alexdmiller** [comment]
@tonsky thanks! In case it's useful, after I ran `brew install ninja` I saw the following build errors:

```
../src/ColorType.cc:1:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
```

I ran `/usr/libexec/java_home -V` to figure out where my Java installs were located and then set my `JAVA_HOME` env variable:

```
JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
```

Now the install script works.

**Comment by tonsky** [comment]
Glad you were able to build it! I added a mention about JAVA_HOME to the README. Thanks!
