### ISSUE TITLE
Running lwjgl.main/-main crashes nREPL

### ISSUE THREAD

**Issue by zikajk** [JetBrains/skija#56]
Is it possible to work with Skija from Clojure nRepl?
I tried to run` (-main)` from your example and it crashes the Repl in Emacs (Cider) on MacOS.
Running by scripts/run.sh works fine though.

```
lwjgl.main> (-main)

*** Closed on Thu Nov 19 13:19:47 2020 ***
```

**Comment by tonsky** [comment]
Yeah, the trick with GUI apps on macOS is that all UI stuff has to be done from the first thread (create window, etc). That’s why the script passes `-XstartOnFirstThread` to the JVM.

The problem with Repls, I assume, is that they create their own threads for handling most operations. It is possible to start GUI app, create windows and _then_ create thread for repl. But it’s not how the defaults are set up, I guess.

**Comment by stathissideris** [comment]
I found this similar issue https://github.com/rogerallen/hello_lwjgl/issues/6 and the commit that implements a workaround that allows working with nREPL. Not sure what would be the most appropriate way to integrate it into the Clojure example, but it looks like a promising direction.
