### ISSUE TITLE
Running skija with Java 8

### ISSUE THREAD

**Issue by Jojal** [JetBrains/skija#57]
Hi everyone,

I was wondering if there is any possibility to make skija wordking with java 8 please ? Maybe a trick or something ? I need to swith to java 11, but due to some legacy code, i still need to wait a bit and i would love to try make skija working with my java 8 app.

Thank's a lot.

**Comment by tonsky** [comment]
Good question—have you tried it? What didn’t work?

**Comment by tonsky** [comment]
This is what we depend on https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html, avaliable since 9. So I guess the minimal version is 9

**Comment by Jojal** [comment]
Yeah i tried. I just modified the pom.xml to change the compiler version from 11 to 8, and i had an error about what you said.
java.lang.ref.Cleaner not found.

Thank you for the answer. Now i think there is no chance that this could be work with java 8.

**Comment by yuhailong626** [comment]
I tried to replace java.lang.ref.Cleaner with sun.misc.Cleaner and it worked.
Like this: 
`
import sun.misc.Cleaner;
public abstract class Managed extends Native implements AutoCloseable {
    public Cleaner _cleaner;

    public Managed(long ptr, long finalizer) {
        this(ptr, finalizer, true);
    }

    public Managed(long ptr, long finalizer, boolean managed) {
        super(ptr);
        if (managed) {
            assert ptr != 0L : "Managed ptr is 0";

            assert finalizer != 0L : "Managed finalizer is 0";

            String className = this.getClass().getSimpleName();
            Stats.onAllocated(className);
            this._cleaner = Cleaner.create(this, new Managed.CleanerThunk(className, ptr, finalizer));
        }

    }

    public void close() {
        if (0L == this._ptr) {
            throw new RuntimeException("Object already closed: " + this);
        } else if (null == this._cleaner) {
            throw new RuntimeException("Object is not managed in JVM, can't close(): " + this);
        } else {
            this._cleaner.clean();
            this._cleaner = null;
            this._ptr = 0L;
        }
    }

    public static native void _nInvokeFinalizer(long var0, long var2);

    public static class CleanerThunk implements Runnable {
        public String _className;
        public long _ptr;
        public long _finalizerPtr;

        public CleanerThunk(String className, long ptr, long finalizer) {
            this._className = className;
            this._ptr = ptr;
            this._finalizerPtr = finalizer;
        }

        public void run() {
            Stats.onDeallocated(this._className);
            Stats.onNativeCall();
            Managed._nInvokeFinalizer(this._finalizerPtr, this._ptr);
        }
    }
}`

**Comment by tonsky** [comment]
Great!

**Comment by Jojal** [comment]
Yeah it's really good ! I'm gonna try that :+1: 
The only thing is we need to make this patch every time there is a new version ? Or could that be handled by the skija team maybe ?

Thanks again !

**Comment by tonsky** [comment]
I don’t know a way to make two different classes for two different JVM versions.

Out of curiosity, what are the reasons that make you stay on Java 8?

**Comment by Jojal** [comment]
Just because of legacy :) I will take time to upgrade my app to java 11 but for huge application it's not so easy to do it unfortunately. That is why, it would have been easier if Skija could work directly with Java 8 in my case.

But it's now good to know that it can works with Java 8.
Thanks again for your help. 
And really good job with Skija. Was waiting for that since a long time :+1:

**Comment by magneticflux-** [comment]
> I don’t know a way to make two different classes for two different JVM versions.

@tonsky Coincidentally, Java 9 introduced exactly that feature! 😄
You can create multi-release jars that include classes specifically for backwards compatibility. If `Cleaner` is the only API needed, I think it would be pretty easy to expose the `sun.misc` API as the modern one on Java 8 and not break anything on newer versions.

There's a great guide for Maven use here: https://www.baeldung.com/maven-multi-release-jars

**Comment by tonsky** [comment]
Great! Do you want to work on that? I’d be happy to review a PR

**Comment by Sm0keySa1m0n** [comment]
Any status on this?

**Comment by luojinrong** [comment]
> Yeah it's really good ! I'm gonna try that 👍 The only thing is we need to make this patch every time there is a new version ? Or could that be handled by the skija team maybe ?
> 
> Thanks again !

@Jojal How do you modified the **scripts** to support compile? When I just replace java.lang.ref.Cleaner with sun.misc.Cleaner and run */script/build.py*, it says there's no options like "--release", "--class-path" and "--module-path". After search I found these options only support in Java 9, cause I'm new in Java that do not have any idea to modify it. So if any help about how to compile it with Java 8.

Thanks in advance!

**Comment by tonsky** [comment]
@luojinrong I am curious what keeps you on Java 8? If you are new, why not start with the latest?

**Comment by luojinrong** [comment]
> 

Cause only I'm new, uhh...but my company use java 8 on its servers. We prefer using skija with java 8 than upgrading java version on servers.

**Comment by tonsky** [comment]
How do you plan to use Skija on the servers? Just curious

**Comment by Lucaskyy** [comment]
I'd like to use Skija with the LWJGL backend on older versions of Minecraft, which still run on Java 8 and cannot be updated due to an outdated Netty dependency.

Is there any workaround for this so I can use Skija with Java 8?

**Comment by Glavo** [comment]
@Jojal @yuhailong626 @magneticflux @Sm0keySa1m0n @luojinrong @Sculas 

[HumbleUI/Skija](https://github.com/HumbleUI/Skija) has provided Java 8 support since 0.109.0.
