### ISSUE TITLE
 Does skija support windows x86?

### ISSUE THREAD

**Issue by yuhailong626** [JetBrains/skija#61]
I noticed that [skia-build](https://github.com/JetBrains/skia-build/releases) is all x64,  how to get windows x86?

**Comment by tonsky** [comment]
You can try building it yourself. Modify what makes sense in build_windows.sh and try running it, let me know how it goes. If something is seriously broken, I’ll be happy to merge a fix.

Just out of curiosity, what’s your use-case?

**Comment by yuhailong626** [comment]
Hi @tonsky ,
I recently noticed that [compose-jb](https://github.com/JetBrains/compose-jb) can support windows&android, and it uses skija, but our application needs to support windows xp, I am investigating its feasibility

**Comment by tonsky** [comment]
Probably possible (unless Skia doesn’t compile to x86, which I doubt), just wasn’t done yet. The second obstacle is that we might write Skija C++ bindings wrong somewhere (assuming primitive sizes which are different on x86). If that’s the case, we’ll see if anything can be done about it.

**Comment by yuhailong626** [comment]
@tonsky , thanks for your answer, is there any plan to support x86 in Skija?

**Comment by tonsky** [comment]
Not actively, but if someone comes up with PR, I’ll take a good look at it and merge if it works. I am not against the idea

**Comment by yuhailong626** [comment]
Thanks,I will try it.
