### ISSUE TITLE
problem running Clojure example on Ubuntu 20.04

### ISSUE THREAD

**Issue by oakmac** [JetBrains/skija#68]
Hello! I am trying to run the [Clojure example](https://github.com/JetBrains/skija/tree/master/examples/clojure) on Ubuntu 20.04 and running into an error:

```txt
oakmac@oakmac-desktop:~/skija/examples/clojure$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

oakmac@oakmac-desktop:~/skija/examples/clojure$ clj -M -m lwjgl.main
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Execution error (UnsatisfiedLinkError) at org.lwjgl.system.Library/loadSystem (Library.java:162).
Failed to locate library: liblwjgl.so

Full report at:
/tmp/clojure-10182201394873438874.edn
```

The full clojure error report can be [found here](https://gist.github.com/oakmac/4800cd92e748e8c012d2976249671866).

Some searching leads me to believe this is not specific to skija, but rather something related to including a library path on the CLI or via `deps.edn` (I am not exactly sure though).

I thought I would make an issue for help and also to document this in case anyone else runs into a similar problem.

**Comment by tonsky** [comment]
Have you built local skija locally?

Alternatively, you can replace `org.jetbrains.skija/skija-native {:mvn/version "0.0.0-SNAPSHOT"}` in deps.edn with `org.jetbrains.skija/skija-macos {:mvn/version "0.6.21"}`

**Comment by oakmac** [comment]
> Have you built local skija locally?

I have not. I was running into trouble with that as well.

> Alternatively, you can replace ... in deps.edn

This is the approach I tried. My `deps.edn` is here: https://gist.github.com/oakmac/275cbe9e95e1b01d0effafa53cdadbc1

**Comment by oakmac** [comment]
I am able to run `examples/lwjgl/scripts/exec.sh` and the window pops up with examples working. Not sure if that is relevant / related or not.

**Comment by tonsky** [comment]
Looks like you need to change `natives-macos` to `natives-linux` for all lwjgl dependencies. I’ll add that to the README

**Comment by oakmac** [comment]
Oh my gosh - duh! That flew right over my head last night :rofl: 

Yes - that works perfectly. For anyone finding this thread changing my `deps.edn` to this worked:

```edn
{:deps {
        ; org.jetbrains.skija/skija-native {:mvn/version "0.0.0-SNAPSHOT"}
        org.jetbrains.skija/skija-linux {:mvn/version "0.6.21"}
        org.lwjgl/lwjgl {:mvn/version "3.2.3"}
        org.lwjgl/lwjgl$natives-linux {:mvn/version "3.2.3"}
        org.lwjgl/lwjgl-glfw {:mvn/version "3.2.3"}
        org.lwjgl/lwjgl-glfw$natives-linux {:mvn/version "3.2.3"}
        org.lwjgl/lwjgl-opengl {:mvn/version "3.2.3"}
        org.lwjgl/lwjgl-opengl$natives-linux {:mvn/version "3.2.3"}
        nrepl/nrepl {:mvn/version "0.8.3"}}

 :mvn/repos {"space-maven" {:url "https://packages.jetbrains.team/maven/p/skija/maven"}}}
```
Then I run `clj -M -m lwjgl.main` and see a rotating square.

Thank you for the help @tonsky !
