### ISSUE TITLE
Binding request

### ISSUE THREAD

**Issue by paternosterHC** [JetBrains/skija#75]
Hi,

would it be possible to add bindings for DirectContext.resetContext so that we can implement Skija into 3D OpenGL applications?
Building Skija through the Docker image sadly doesn't work properly for me, so I can't add it myself :(

Thank you!

**Comment by tonsky** [comment]
Sure, will add.

P.S. what didn’t worked with Docker? I would like it to stay current

**Comment by paternosterHC** [comment]
Thank you!

Building with docker shows this:
`bash: cannot set terminal process group (1): Inappropriate ioctl for device
bash: no job control in this shell
`

Trying to use the resulting library results in an
`java.lang.IllegalArgumentException: Library file icudtl.dat not found in /`
