### ISSUE TITLE
When install have error

### ISSUE THREAD

**Issue by alezzigo** [JetBrains/skija#76]
Hi,
I install with maven 
It have errors 
![Capture](https://user-images.githubusercontent.com/26524788/102711865-452b1380-42ef-11eb-9515-47e771ba7fba.PNG)

I dont know it, Can you fix help me?
Thanks!
Alexi

**Comment by tonsky** [comment]
I think this is related to the use of Lombok in Skija https://projectlombok.org/. Lombok generates getters and setters on the fly. In IntelliJ there’s plugin that supports that, maybe there’s something for Eclipse too?

**Comment by alezzigo** [comment]
Thank Tonsky
