### ISSUE TITLE
`.drawString` crashes the JVM when passed a null paint

### ISSUE THREAD

**Issue by phronmophobic** [JetBrains/skija#81]
I created a repro in https://github.com/phronmophobic/membrane-skija-example

code: https://github.com/phronmophobic/membrane-skija-example/blob/main/src/com/phronemophobic/issues.clj#L30

run with: `clj -X com.phronemophobic.issues/drawstring-crash-null-paint`
it should behave similar to: `clj -X com.phronemophobic.issues/drawstring-works`

**Comment by tonsky** [comment]
I don’t think it’s a good idea to treat null here as a default Paint. Default Paint might be useful for quick testing, but for anything else, it’s not a good idea to rely on default values. I am thinking of checking for null instead and throwing an exception. Crashing should not happen here, I agree.

**Comment by tonsky** [comment]
If you need something like this, just create a global default Paint and use it in places like this.

**Comment by phronmophobic** [comment]
Yea, throwing an exception does seem like a better route.
