### ISSUE TITLE
Image formats HEIF, AVIF

### ISSUE THREAD

**Issue by Solido** [JetBrains/skija#90]
Hi !

Stumbled upon this Skia release note for m88
 * Add AVIF support to SkHeifCodec.

Got a lot of interest for details preservation.

Thank you Tonsky

**Comment by tonsky** [comment]
Thanks, I’ll look into it

**Comment by tonsky** [comment]
Seems like it’s not included in Skia, but depends on Android implementation https://android.googlesource.com/platform/frameworks/av/+/master/media/libheif/include/HeifDecoderAPI.h

Opened a ticket: https://bugs.chromium.org/p/skia/issues/detail?id=11733

Let’s hope
