### ISSUE TITLE
Build skija have an error

### ISSUE THREAD

**Issue by hanjinfeng0309** [JetBrains/skija#92]
I want to install skija locally in `.m2` follow [Building Skija from scratch](https://github.com/JetBrains/skija#building-skija-from-scratch), but it show me "`jni.h` no such file or directory". 
![image](https://user-images.githubusercontent.com/63445267/106711125-000a3900-6632-11eb-955d-88db02342080.png)

Then display this error while I compile `skija/native` in clion: 
![image](https://user-images.githubusercontent.com/63445267/106711648-c71e9400-6632-11eb-9ff5-98b37c6b0aaa.png)

I'm not goot at c++ and cmake, I don't know how to resolve this problem.

my env: 
```
archlinux: 5.10.11-arch1-1
git: 2.30.0
cmake: 3.19.4
ninja: 1.10.2
jdk: openjdk11
maven: 3.6.3
```

**Comment by tonsky** [comment]
You need JAVA_HOME environment variable set. Sorry the error is confusing, I’ll clarify it in the README

**Comment by hanjinfeng0309** [comment]
Sorry can not reply you Immediately because I caught a cold yesterday. And I prepare to use the [remote maven repository](https://github.com/JetBrains/skija#using-skija).
Now I have a few problem: 
1. I clone the latest skija repository, there is need to correct `./native/script/build.sh` and `./native/script/install.sh` to `./native/script/build.clj` and `./native/script/install.clj` in `./script/install.sh`. (now time is 2021-02-05 09:37:15 GMT+0800)
2. `/usr/bin/env: "bb"`: no such file or directory. Sorry I never use this script, do I need install any software or package? It looks like you need to modify the `README.md`.

**Comment by hanjinfeng0309** [comment]
3. Could you add skija repository for the latest version to [Maven Repository](https://mvnrepository.com/), now all the versions in there are out of date.

**Comment by tonsky** [comment]
Sorry, the script is https://github.com/babashka/babashka/releases, I’ll update the README soon
