### ISSUE TITLE
How can I use SkSVG backend?

### ISSUE THREAD

**Issue by madhead** [JetBrains/skija#93]
Tag: Question

I see there is a way to render `SVG` to a `Canvas` with Skija, like:

```kotlin
val svg = Data.makeFromBytes(…SVG…)
val dom = DOM(svg)

dom.render(canvas)
```

But is it possible to output `SVG` from Skija using `SkSVG` backend?

**Comment by tonsky** [comment]
Seems like SkSVGCanvas is whay you need. There’s no JVM bindings for that yet, but should be easy to add. https://github.com/google/skia/blob/master/include/svg/SkSVGCanvas.h

**Comment by madhead** [comment]
@tonsky,

I'm kind of interested contributing this feature :) But I've never used JNI.

I see the only method of SkSVGCanvas — [`Make`](https://github.com/google/skia/blob/7cb0f6e9702a1929efa9aef419835b12daae2ed0/include/svg/SkSVGCanvas.h#L33) accepts a pointer to a `SkWStream`, which is [defined](https://github.com/google/skia/blob/7cb0f6e9702a1929efa9aef419835b12daae2ed0/include/svg/SkSVGCanvas.h#L13) in the same file. Is it the same as the one from [`core/SkStream.h`](https://github.com/google/skia/blob/7cb0f6e9702a1929efa9aef419835b12daae2ed0/include/core/SkStream.h#L227)? Is there an existing Java equivalent for it, or a new wrapper should be created? If so, it doesn't look so easy now…

BTW, do you write that cc classes, like `native/src/svg/DOM.cc` with JNI bindings or could they be auto-generated somehow?

Thanks!

**Comment by tonsky** [comment]
Yeah, SkWStream would be a really tricky part. Ideally it should be converted to OutputStream on Java side, but there’s no precedent yet in Skija repo. I might look into it myself.

*.cc are hand-written. There’s a tool in java distro that can generate function headers from native method definitions in java classes, but I don’t use it. It’s pretty straightforward.

**Comment by tonsky** [comment]
Ok, I made the initial implementation. You should be able to provide OutputStream, draw and get SVG code out. Version 0.89.24. Usage example here https://github.com/JetBrains/skija/blob/0c350898f2d12610210d5de3f753cccf2729ae37/shared/src/test/java/org/jetbrains/skija/svg/SVGCanvasTest.java

**Comment by madhead** [comment]
Cool, thank you!
