### ISSUE TITLE
BMP on linux

### ISSUE THREAD

**Issue by harold** [JetBrains/skija#96]
Hi! First, thank you for Skija, a sane api on a great lib; I am very grateful.

I am able to write out `.png` images on linux, but not `.bmp` (EncodedImageFormat/BMP).
 - Is this expected?

If so, I wonder where this limitation comes from.

This seems to indicate that .bmp might work on Mac?
 - https://github.com/JetBrains/skija/blob/48c3d22e68853e2aba0703387d3e2ac211580476/shared/src/main/java/org/jetbrains/skija/Image.java#L53-L54

Is that correct?

Thank you in advance for your time and consideration, this library is great.

@cnuernber - potentially relevant to your interests.

**Comment by tonsky** [comment]
Hi @harold, I’m not sure how formats are distributed between OSes yet (and why). I’ll look into it, got another question about ICO today, probably related

**Comment by harold** [comment]
Very cool. `.bmp` could be a big speedup for me over `.png` because downstream processes prefer uncompressed frames anyway, so any time not doing `deflate/inflate` would be saved.

**Comment by tonsky** [comment]
Looks like Skia relies on OS to do the actual encoding.

You can see in e.g. https://github.com/google/skia/blob/d0ce14942bd67bbde794bdddc0a1342183680f09/src/ports/SkImageEncoder_CG.cpp that on macOS CoreGraphics is used and it just supports more formats.

If none of those are available, it resorts to cross-platform libraries, of which it includes jpeg, png and webp: : https://github.com/google/skia/blob/d0ce14942bd67bbde794bdddc0a1342183680f09/src/images/SkImageEncoder.cpp#L37-L84

My advice would be to get a Java library that can encode raw pixel data to BMP (I am sure there are some). After that, both Bitmap and Image expose raw pixel data via `peekPixels` method.

**Comment by harold** [comment]
Noted, thanks for looking into it.
